### ISSUE TITLE
Allowing for "fixing" data

### ISSUE THREAD

**Issue by strhea** [ADAPT/Standard#102]
During the mid-year meeting there were some concerns raised about the ability to correct for bad offsets. Our current coverage shape approach would require the geospatial translation operation to move the shape (laterally or along-track) based on the heading. While possible, this is complex. This might we more easily solvable by including the section center latitude and longitude as representation. This still does NOT require the offsets to be tracked/preserved since the point has been resolved to the section center.

**Comment by knelson-farmbeltnorth** [comment]
My initial reaction is that this is some of the same pushback that we all felt upon contemplating changing the model away from points and offsets.  We have historic frames of reference, and it is uncomfortable to think that we are losing control over the data.   Looking at it from our principle that ADAPT is the transfer data from one party to another, there is nothing implicit in that specifying that ADAPT also contain all of the necessary antecedents so that data can be reconstructed from first principles.   

In this case, if a consumer suspects that offsets are wrong, then they should request the source data from the provider in ISOXML and from there build their own polygons.
