### ISSUE TITLE
Operation Type Definitions

### ISSUE THREAD

**Issue by knelson-farmbeltnorth** [ADAPT/Standard#133]
I've added definitions to the items in the Operation Type Data Type Definition below.   

In so doing, I'm also recommending a few changes.  

1.  Mowing, Wrapping and Transport and Vehicle Data were formerly grouped as "MISC"   
  a. I've recategorized Mowing and Wrapping into Harvest. I believe these items were put in the list as haying operations and not for any other non-field purpose. 
  b. I've further consolidated Swathing and Mowing.  These items may have been separate from a machinery viewpoint, but arguably the activities have a common definition for our purposes.
  c. I've renamed/promoted "Transport/Vehicle Data" to a top level item "Vehicle_Data_Collection".  The "Data Collection" terminology is a carryover from the ADAPT Framework and it would seem to do a better job of naming the operation.

2. I've added "_GENERAL" to all top level types for consistency

--
Proposed Definitions:

UNKNOWN (not defined)

APPLICATION_GENERAL: 
Applying input(s) to a Field for purposes not otherwise specified in this list.

APPLICATION_FERTILIZING: 
Applying crop nutrition input(s) to a Field.

APPLICATION_SOWING_AND_PLANTING:
Introducing the seeds or other plant material into a field.

APPLICATION_CROP_PROTECTION: 
Applying crop protection input(s) to a Field.

APPLICATION_IRRIGATION:
Applying water to a Field for the purpose of irrigation.

HARVEST_GENERAL: 
Harvesting a Field through means not otherwise specified in this list, including combining

HARVEST_BALING: 
Harvesting a crop into bales

HARVEST_FORAGE_CHOPPING: 
Harvesting a Field with a Forage Chopper

HARVEST_MOWING_AND_SWATHING: 
Cutting the crop to be dried in the Field before a subsequent harvest operation.

HARVEST_WRAPPING: 
The activity of wrapping the harvested crop in protective material

OBSERVATION_GENERAL: 
A Field Observation activity such as scouting or soil testing

TILLAGE_GENERAL: 
Mechanical preparation of soil for cultivation

VEHICLE_DATA_COLLECTION_GENERAL: 
The activity of collecting data from the tractor or other vehicle, often alongside another Operation Type or in transport between Fields.

**Comment by crakerb-ship-it** [comment]
Would there be any value in aligning to AEF equipment types from the ISOBUS database:
![image](https://github.com/ADAPT/Standard/assets/69859591/08f303b2-6ec9-4065-80c1-f0f420c0e75f)

**Comment by knelson-farmbeltnorth** [comment]
Lots of discussion on the Harvest categorizations in 13 December 2023 meeting.  One idea was to things like mowing, raking and tedding hay, swathing grain, digging peanuts and topping potatoes into a HARVEST_PREPARATION category.  Another was simply to call everything HARVEST, although multiple such operations over the same ground adds confusion in interpreting the data.  Leaving this open for further discussion.

**Comment by crakerb-ship-it** [comment]
I think I may have gone way too far down the rabbit hole here but my two cents is to consolidate all the above HARVEST 's to: HARVEST_PREPARATION, HARVEST_GENERAL and add STORAGE_LOGISTICS, MAINTENANCE and maybe TRANSPORT_HAULING.

Personally, I like the idea of consolidating several of what are currently listed to a HARVEST_PREPARATION type for any operations that happen in the field but nothing is removed from the field like cutting, swathing, raking, merging, lifting, etc. HARVEST could then encompass the operations where the crop transforms into the harvested product and is packaged or removed from the field.

The post harvest piece is a little more difficult to define for me and feels like there should maybe be a couple types. I would propose STORAGE_LOGISTICS for operations like wrapping, bagging, packing (e.g. silage pile/bunker), or if someone tracked the use of a tractor to power an auger moving grain into bin/dryer. This group would also include collecting bales dropped in a field, piling beets harvested at the headland, basically transport operations that don't leave the field. A grain cart hauling from combine to transport vehicle would fall in this category too. 

To me this raises the question do we need a separate TRANSPORT_HAULING type or does that fall under VEHICLE_DATA_COLLECTION_GENERAL or just include under STORAGE_LOGISTICS? Thinking about moving forage from the field to the silo or bunker, manure from storage to the field, or hauling grain to the bin via tractor and wagon? I know for some carbon programs they want to have a record of how far grain was trucked to the elevator to account for the footprint of the semi's diesel use and it is common for a tractor and wagon(s) to preform that operation in many parts of the world. So while this may not be logged much today could be a requirement in the not too distant future.

There may be merit for some type of of MAINTENANCE operation group as well. This could cover mowing waterways like we discussed during the call as something different than HARVEST_PREPARATION since there is no intention to collect a harvested product afterward. There are other operations like shredding corn stalks or mowing a cotton field in lieu of tillage after harvest since that is a regulatory requirement (for cotton) in some areas I believe. Other operations like rebuilding borders in flood irrigated fields, land leveling a field, picking rocks, or shaping beds could go here as well since they do not exactly fit as tillage in my mind. 

It is a messy quagmire to sort this all out for sure and there will be exceptions to everything I suggested but I think with some of the reporting requirements on the horizon it would be helpful to have a little more granularity than putting everything under HARVEST.

**Comment by knelson-farmbeltnorth** [comment]
@crakerb-ship-it I white-boarded ideas after this morning's discussion and came up with some similar conclusions.  

VEHICLE_DATA_COLLECTION_GENERAL is the operation type for tractor telematics, so if there is no data collected/logged from the pre/post-harvest operation, then that is all there is.   

"Harvest Preparation" would be a logged Operation if there was data present.   That could be a manual entry.  E.g., We store summary fuel data from the tractor, but also a manual record of having raked 40 acres.   In future if these sorts of implements start measuring/logging something, then "Harvest Preparation" is also the place for it.  One last thought that came up was that spraying a non-selective herbicide to dry down a crop could also be considered "Harvest Preparation" rather than "Application - Crop Protection."  

I like your observation of the transition from crop to harvested product, although I can also foresee differences of perspective on when that happens.  In practical terms, the point of threshing/chopping/baling is "harvest per se," where equipment can today measure the yield and where we can still (fairly easily) correlate the harvest to a spatial footprint on the field.

The question with "Post Harvest" is where do we stop?  We've used the constraint that ADAPT is today limited to data associated to cultivated ground.  Does that mean so long as we can track data to an individual Field we are inside our scope?

**Comment by knelson-farmbeltnorth** [comment]
I'm proposing the following updated list for continued discussions.  I've replaced the harvest categories with 3 defined in-field types and purposely omitted the "general" term from harvest.   Per @crakerb-ship-it's comments above, I've created a new type alongside tillage.  

UNKNOWN (not defined)

APPLICATION_GENERAL:
Applying input(s) to a Field for purposes not otherwise specified in this list.

APPLICATION_FERTILIZING:
Applying crop nutrition input(s) to a Field.

APPLICATION_SOWING_AND_PLANTING:
Introducing the seeds or other plant material into a field.

APPLICATION_CROP_PROTECTION:
Applying crop protection input(s) to a Field.

APPLICATION_IRRIGATION:
Applying water to a Field for the purpose of irrigation.

FIELD_PREPARATION_GENERAL:  Non-tillage activities to prepare a field for cultivation including chopping stover, picking rocks, leveling a field, building borders in flood-irrigated fields, shaping beds, etc.

FIELD_PREPARATION_TILLAGE:  Mechanical digging of soil for future cultivation

HARVEST_PRE_HARVEST – In-field activities in preparation of harvest such as swathing grain, mowing, ranking and tedding hay, and topping or turning over root crops.

HARVEST:  The specific activity of gathering the cultivated crop from its growing location converting it into a product.   Examples include combining grain, chopping forage, baling hay, picking cotton or fruit.    

HARVEST_POST_HARVEST:  In-field activities following actual harvest such as carting grain, wrapping and hauling bales, etc.

OBSERVATION_GENERAL:
A Field Observation activity such as scouting or soil testing

VEHICLE_DATA_COLLECTION_GENERAL:
The activity of collecting data from the tractor or other vehicle, often alongside another Operation Type or in transport between Fields.  Examples include fuel usage and speed.

**Comment by knelson-farmbeltnorth** [comment]
Updated definitions from discussion in 3 January 2024 meeting to my earlier proposal:

FIELD_PREPARATION_TILLAGE:  Ground engaging operation to size and incorporate residue or alter the soil structure for future cultivation.

HARVEST_PRE_HARVEST: In-field activities in preparation of harvest that are tracked separately, usually involving separate passes over the field from the harvest itself.  Examples include swathing grain, mowing, raking and tedding hay, and removing foliage from or turning over root crops. 

HARVEST_POST_HARVEST: In-field activities following the actual harvest that are tracked separately, usually involving separate passes over the field from the harvest itself.   Examples include carting grain, wrapping and hauling bales.

APPLICATION_GENERAL:
Applying input(s) to a Field for purposes not otherwise specified in this list, or involving individual product mixes that cross types.   Examples include spreading lime, and applying a product mix with a liquid fertilizer carrier and crop protection ingredients.  Seeds with crop protection treatments, however, should be classified as APPLICATION_SOWING_AND_PLANTING.  Also note that where multiple products of different types are applied in a single pass, data should be configured in separate operations by type.

**Comment by knelson-farmbeltnorth** [comment]
Latest changes agreed in 17 January 2024 meeting
