### ISSUE TITLE
Contact changes

### ISSUE THREAD

**Issue by kelly-nelson** [ADAPT/Standard#27]
Person.CombinedName is omitted as redundant and confusing as to which properties to fill.

Contact.Number (email/phone) becomes Value

**Comment by brycehemme** [comment]
CombinedName is useful when source systems can't cleanly parse name parts. Not sure that should change the direction to remove CombinedName, though.

I'm not sure I follow how Contact.Number is intended to be used in comparison to the ContactInfo class. Any further insight others can share?

**Comment by strhea** [comment]
ContactInfo contains a "contacts" array of Contact objects. Instead of having multiple properties on the ContactInfo object for "landline", "cell", or "fax" numbers it was abstracted to the Contact class with the ContactTypeEnum to make the meaning explicit. One thing I hate about it though is that "email" was included in that abstraction.

**Comment by knelson-farmbeltnorth** [comment]
What if we abandoned the ContactTypeEnum in favor of one string field to identify a contact, and another as its description.

Landline and fax as defined items can only become more obsolete.    In another decade, we might have included "Telex" in the same vein, and its presence in the model today would make the model itself appear outdated.

**Comment by knelson-farmbeltnorth** [comment]
Changing name of issue.  Person changes are handled in #7 

For ContactInfo, I recommend we change Contact to "Contact Method" and have two text fields as I proposed above.  One for Value and one for Description.

Also, I don't know what to make of Location on Contact Info.   Is this intended so that we may geo-reference the address?
