### ISSUE TITLE
Should the model prescribe a single approach per use case or allow for multiple approaches thought to be in use?

### ISSUE THREAD

**Issue by knelson-farmbeltnorth** [ADAPT/Standard#66]
On attempting to define several entities in the model, it is clear that there was intent to allow implementers multiple ways to do things.    

E.g., a Field references both a FarmId and a GrowerId so that systems that do not have Farm in their operational hierarchy can model Fields as children of a Grower.   In this case, the burden of making sense of the data falls on the consumer, who must anticipate and provide for the multiple cases, e.g., creating a single Farm for each Grower within the consuming system for source data that lacks Farms.   

The alternative approach would be for the model to mandate Farms, and any source system that lacks Farms would themselves need to create the single Farm per Grower.   The advantage to this is that the source system understands their own data and can appropriately make allowances to model it accurately.

This issue also occurs through the Documents.   Today a Work Item (prescribed agronomic action) can be scoped to any of a Grower, Farm, Field or CropZone depending on the inclination of the source data.   If we limit such scoping to a Field (for e.g., tillage where a crop is not known/relevant) or CropZone (for cases where the crop is known), data consumers will have a predictable set of circumstances to provide for.   For the source system recording a vague Work Item (all Fields in specific Farm should be fertilized as of a certain date) then the Work Item should be duplicated once per Field.

This item is related to #38 and is a prerequisite principle to providing cogent definitions to most of the document classes #36.

**Comment by strhea** [comment]
I THINK I agree for the most part, but let me restate things to see if I understand.

1) Force users to create a "virtual farm" object if they don't use farms in their hierarchy in order to simplify the handling logic on the consumer side. I'm ok with this. If we take this approach, I would like to add a property to Farm that could be explicitly set as "virtual" to communicate that fact to the consumer.

2) I think CropZone is a little stickier. Not everybody uses that lowest level of the hierarchy. Many systems document their field operations exclusively at the field level. While I am a strong advocate for the CropZone concept, I don't think we can mandate its use that way. The description of land/area usage in a field operation needs to support both the Field & CropZone objects.

2.5) I think there is a conversation to be had about "single field" vs "multi field" documents. This was one of our original points of discussion/disagreement in the initial implementation.  Note how at the document level, there is a singular Grower but then arrays of Farm/Field/CropZone but at the work item level they are all singular. It's IMPLIED that the document level properties are meant to be populated by aggregating the member work items.

3) I agree that Document makes the most sense as an abstract base class. So far, all of the core document types are composed in a very similar way that captures the PLANNED or ACTUAL use of resources in the context of cultivating a crop.

**Comment by knelson-farmbeltnorth** [comment]
Universal agreement on September 14 meeting:  ADAPT will not allow options for different modeling approaches.  There is to be one agreed-upon method of modeling any use case.   E.g., if a source system doesn't have Farm, so long as we have Farm in ADAPT that system must fill it with a something to conform to the ADAPT model vs. ADAPT offering the flexibility to omit it at the discretion of the implementer.
